sudo: required
dist: trusty
group: deprecated-2017Q2

language: python

python:
  - "3.4"
  
virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -yq xvfb gir1.2-gtk-3.0 python3-gi-cairo python-mpltoolkits.basemap python3-numpy python3-matplotlib python3-sphinx python-libhamlib2 python3-flake8
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

install:
  - sudo pip3 install . 

before_script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - echo $PYTHONPATH
  - flake8 pyqso
  - flake8 tests
  - flake8 bin
  
script:
  - make test
  - make docs
  - sudo make clean
